SCREW_MAIN_DIAMETER = 3.5;
SCREW_MAIN_EMBED = 2;
SCREW_HEAD_DIAMETER = 6.9;
SCREW_HEAD_EMBED = 2.6;
SCREW_FREE_SPACE = 100;
SCREW_ARC_FN = 20; // see https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Other_Language_Features#.24fa.2C_.24fs_and_.24fn

WALL_ATTACHMENT_THICKNESS = SCREW_MAIN_EMBED + SCREW_HEAD_EMBED;
